import courses from './courses.json';
import originalReadings from './readings.json';
export type Reading={id:string;area:string;topic:string;title:string;short:string;source:string;date:string|null;url:string;kind?:'analysis';sections:{title:string;body:string}[];references?:{author:string;title:string;date:string|null;url:string}[]};
export const areas=[{id:'work',label:'工作',description:'品牌、营销与市场，理解科技公司的增长。'},{id:'capability',label:'个人能力',description:'从 Vibe Coding 出发，也练习理解经济与商业。'},{id:'growth',label:'心灵成长',description:'心理学、自我理解，以及值得慢读的文学与社科。'}];
export const topics=[{id:'gtm',label:'GTM',description:'产品怎样进入市场，找到客户与增长路径。'},{id:'brand',label:'品牌市场',description:'品牌定位、营销传播与市场策略。'},{id:'market',label:'市场盯盘',description:'技术与公司的变化，对客户需求、竞争和商业机会意味着什么。'}];
const guides:Reading[]=[
 {id:'segment-market-fit',area:'work',topic:'gtm',title:'Segment 如何找到产品与市场的契合点',source:'Y Combinator',date:'2018-09-06',url:'https://www.ycombinator.com/blog/peter-reinhardt-on-finding-product-market-fit-at-segment',short:'从失败的产品、客户访谈，到开发者驱动的市场进入策略。',sections:[{title:'读这篇，先带着一个问题',body:'用户说“这个主意不错”，与用户真的开始使用，中间隔着什么？这份创始人访谈记录了 Segment 如何从最初的产品转向数据路由服务，适合把产品验证、客户需求和市场进入策略放在一起阅读。'},{title:'从真实使用里找信号',body:'访谈中，团队起初投入很大，却没有得到持续使用。后来，一个用于连接分析工具的小型开源项目吸引了用户。判断需求时，值得区分礼貌的反馈、功能建议与已经发生的使用行为。前两者能提示方向，最后一种更接近产品正在解决的问题。'},{title:'谁把产品带进一家公司？',body:'Segment 的早期进入路径与工程师有关，而它服务的需求也涉及营销和产品团队。阅读时可以分别标出“发现产品的人”“推动采用的人”和“使用结果的人”。对 B2B 的 GTM 来说，这些角色可能不同，传播对象与商业价值需要接得上。'},{title:'怎样把案例用回自己的工作',body:'选一个你熟悉的产品，写下它希望接触谁、解决什么已有问题，以及哪一个真实动作能证明对方需要它。这里的提问是本站阅读练习；访谈是一家公司的历史经验，不是适用于所有市场的固定公式。原访谈还包含客户访谈、产品表达及上线测试的讨论，可继续读英文实录。'}]},
 {id:'self-compassion-difficulty',area:'growth',topic:'psychology',title:'为什么善待自己，有时很难？',source:'UC Berkeley · Greater Good',date:'2022-10-26',url:'https://greatergood.berkeley.edu/article/item/why_is_self_compassion_so_hard_for_some_people',short:'理解自我关怀的阻力，也看见人与人之间的差异。',sections:[{title:'先允许“这句话对我没用”',body:'对自己说一句温柔的话，并不保证立刻感觉好一些。Caroline Benner 在这篇文章中讨论了自我关怀可能遇到的阻力，并采访了相关研究者。它提供的一个有用视角是：一种练习没有帮助到你，不必立即解释成你做得不够好。'},{title:'关怀也可以是一个具体行动',body:'文章区分了在脑中安慰自己与通过行动照顾当下需要。阅读时可以留意：它不是要求每个人都采用同样的想象或语言练习，而是讨论人们在不同经历下可能有不同反应。'},{title:'读完后，留下一个观察',body:'回想一次有人安慰你、但你并没有更轻松的时刻。当时缺的是理解、陪伴，还是一件实际的帮助？这只是本站给出的阅读问题，不是心理评估。涉及个人经历时，不需要为了完成阅读而勉强解释自己。原文中的研究解释与练习条件值得结合上下文阅读。'}]},
];
export const readings:Reading[]=[...originalReadings as Reading[],...guides];
export const catalog=[...courses.map(lesson=>({id:lesson.id,area:'capability',type:'course' as const,lesson})),...readings.map(reading=>({id:reading.id,area:reading.area,type:'reading' as const,reading}))];
export {courses};
